#!/usr/bin/env bash

# https://github.com/mauriciojost/mavarduino
#
# Mavarduino Version Bumper
# 
# Control Version Bumps and ease the flow for creating them.
#

export BUMP=${1:-PATCH} # can be MAJOR, MINOR or PATCH

curr_dir=$(dirname $(readlink -e $0))
source $curr_dir/source.sh

CURR_BRANCH=`git rev-parse --abbrev-ref HEAD`
if [ "$CURR_BRANCH" != "master" ]
then
  echo "Must be in master branch to proceed (we are in $CURR_BRANCH)"
  exit 1;
fi

function inc() {
  local i=$1
  echo `echo $i + 1 | bc`
}

echo "### Parsing current version ..."
export VERSION=`cat library.json |  jq  .version | sed 's/"//g'`


export NEW_VERSION=`bump $VERSION $BUMP`

echo "### Creating commit and tags for new version: $NEW_VERSION ..."
sed -i "s/$VERSION-SNAPSHOT/$NEW_VERSION/g" library.json 
sed -i "s/$VERSION/$NEW_VERSION/g" library.json 
git add library.json
git commit -s -m "Bump to $NEW_VERSION"
git tag "$NEW_VERSION" -m "$NEW_VERSION"

echo "### Pushing to git..."
git push --follow-tags

echo "### Done."

