#!/usr/bin/env bash

# https://github.com/mauriciojost/mavarduino
#
# Mavarduino Symlinks Creator
# 
# Creates symlinks to mavarduino scripts into your project directory, so that they can be called conveniently.
#

find .mavarduino -executable -type f -maxdepth 1 | grep -v create_links | xargs -I% ln -sf % .
