#!/usr/bin/env bash

# https://github.com/mauriciojost/mavarduino
#
# Mavarduino Code Formatter (based on clang-format-3.7)
# 
# This script will perform code formatting based on the 
# provided clang configuration file.
#

find src/ test/  -type f | xargs -I% clang-format-5.0 -style=file -i -fallback-style=none %

