#!/usr/bin/env bash

trap ctrl_c INT

function ctrl_c() {
  echo "** Trapped CTRL-C"
  exit 0;
}

arg=serialports
#arg=device
  
export PORT=$1
for i in `seq 1 10000`
do
  pio -f -c atom $arg monitor --raw --port /dev/ttyUSB$PORT -b 115200 | libs/log4ino-arduino/extras/pretty-log | ts | tee .serial.log
  sleep 1
done
