#!/usr/bin/env bash

set -x 
set -e

simulator_binary=.mavarduino.simulator.bin
PROFILE=${1:-profiles/simulate.prof}

root_dir=`pwd`
config_file=mavarduino.conf
libs_dir=$root_dir/libs
src_dir=$root_dir/src
rm -f $simulator_binary

source "$config_file"

VERSION=$(cat library.json | jq -r .version)
COMMIT_ID="`git rev-parse --short HEAD`"
PROJ_VERSION_ID="$VERSION-$COMMIT_ID" 

PARAM_FLAGS="-D X86_64 -D PROJ_VERSION=$PROJ_VERSION_ID `cat $PROFILE | grep -v '^#'`"

simulator_flags="-U ARDUINO $PARAM_FLAGS"

rm -f $simulator_binary

g++ -Wno-deprecated-declarations -g -ggdb -o $simulator_binary $simulator_flags $simulator_src $simulator_headers $simulator_libs
shift
./$simulator_binary $@
#gdbtui ./$simulator_binary

rm -f $simulator_binary
