#!/usr/bin/env bash

set -x 
set -e

simulator_binary=.mavarduino.simulator.bin

function usage() {
  echo "usage: TODO"
}

PROFILE="profiles/simulate.prof"
while getopts p:a:h option
do
  case "${option}"
  in
    p) PROFILE=${OPTARG};;
    a) ARGS=${OPTARG};;
    h) usage
  esac
done

root_dir=`pwd`
config_file=mavarduino.conf
libs_dir=$root_dir/libs
src_dir=$root_dir/src
rm -f $simulator_binary

source "$config_file"

VERSION=$(cat library.json | jq -r .version)
COMMIT_ID="`git rev-parse --short HEAD`"
PROJ_VERSION_ID="$VERSION-$COMMIT_ID" 

PARAM_FLAGS="-D X86_64 -D PROJ_VERSION=$PROJ_VERSION_ID `cat $PROFILE | grep -v '^#'`"

simulator_flags="-U ARDUINO $PARAM_FLAGS"

rm -f $simulator_binary

g++ -Wno-deprecated-declarations -g -ggdb -o $simulator_binary $simulator_flags $simulator_src $simulator_headers $simulator_libs
./$simulator_binary $ARGS
#gdbtui ./$simulator_binary $ARGS

rm -f $simulator_binary
